### ISSUE TITLE
Spam.

### ISSUE THREAD

**Issue by ChavitaHD** [xxyy/quietcord#3] opened 2015-10-11 09:14 UTC
Hello, I tested this local and it did work, but after putting it on my live server it spams:
http://i.imgur.com/nsut19v.png
What is the issue?

**Comment by xxyy** [comment] 2015-10-11 09:37
Hi,
thanks for your report. I do not know how this plugin would output that
kind of messages. Are you 100% positive it's not another plugin doing that?
QuietCord should prefix all its messages with [QuietCord].

If this is sensible in your environment, try removing all plugins but
QuietCord and see if the issue persists. I recommend doing this late at
night, when no players are online.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by ChavitaHD** [comment] 2015-10-11 16:59
Well it only happens on a refresh on the servers list so on a ping.

**Comment by xxyy** [comment] 2015-10-11 17:03
It might be debug messages by another plugin. I am quite positive that
these messages are not produced by QuietCord. Have you tried running the
server without other plugins, or without QuietCord? If the issue persists
without QuietCord installed, we can be sure that it is not causing these
weird messages. Please test that when you can.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by ChavitaHD** [comment] 2015-10-11 17:04
I am going to do said test.

**Comment by xxyy** [comment] 2015-11-02 11:33
Seems like it could be caused by the plugin ServerInfo by joehot200. The issue has been fixed in the latest version of the plugin: https://www.spigotmc.org/threads/serverinfo.7362/page-7#post-1098362

**Closed by xxyy** 2015-11-02 11:33 UTC
